packages:
    - 'html-css/**'
    - 'javascript/**'
    - 'php/**'
    - 'typescript/**'

catalog:
    '@biomejs/biome': ^1.9.4
    sass-embedded: ^1.86.3
    stylelint: ^16.14.1
    stylelint-config-html: ^1.1.0
    stylelint-config-property-sort-order-smacss: ^10.0.0
    stylelint-config-standard: ^38.0.0
    stylelint-order: ^7.0.0
    vite: ^6.3.2
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router-dom: ^7.5.1
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    '@vitejs/plugin-react': ^4.4.1
