packages:
    - 'html-css/**'
    - 'javascript/**'
    - 'php/**'
    - 'typescript/**'

catalog:
    '@biomejs/biome': ^2.0.6
    '@angular/common': ^19.2.0
    '@angular/compiler': ^19.2.0
    '@angular/core': ^19.2.0
    '@angular/forms': ^19.2.0
    '@angular/platform-browser': ^19.2.0
    '@angular/platform-browser-dynamic': ^19.2.0
    '@angular/router': ^19.2.0
    '@angular-devkit/build-angular': ^19.2.0
    '@angular/platform-server': ^19.2.0
    '@angular/cli': ^19.2.0
    '@angular/ssr': ^19.2.0
    '@angular/compiler-cli': ^19.2.0
    bootstrap: ^5.3.7
    sass-embedded: ^1.89.2
    stylelint: ^16.21.0
    stylelint-config-html: ^1.1.0
    stylelint-config-property-sort-order-smacss: ^10.0.0
    stylelint-config-standard: ^38.0.0
    stylelint-order: ^7.0.0
    parcel: ^2.15.4
    vite: ^7.0.0
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router-dom: ^7.5.1
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    '@vitejs/plugin-react': ^4.6.0
