ALTER TABLE `utilisateurs` ADD COLUMN `id_utilisateur` INT AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `tvs` ADD COLUMN `id_tv` INT AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `smartphones` ADD COLUMN `id_smartphone` INT AUTO_INCREMENT PRIMARY KEY FIRST;
